### PR TITLE
Create FeaturedLink and FeaturedLinkDetails components

### LINKED ISSUE #54: Create featured link component
### 💡 Description

We currently have multiple variations of the featured link component employed within the portal-wp repo; however we have now consolidated the design of the this component across the different pages, reducing the variances between them. So, we can now employ a single component with some optional features to cover the search page and directory page implementations that need additional columns of data.

### ⚔️ Parent Epic / Related Tickets

_No response_

### PR DESCRIPTION
**Pull request by anilnatha**
## 🗒️ Summary

Created a new set of components called `FeaturedLink` and `FeaturedLinkDetails` that match our Figma designs where we provide a list of items that have a title and description, an optional set of columns, and a link where the user should be sent if they click the title or the arrow button. The FeaturedLinkDetails component renders the view that is shown when the expand button is clicked in the FeaturedLink component.

## ⚙️ Test Data and/or Report

* Ran a build to verify no linting or build errors were present.

## ♻️ Related Issues

Fixes #54

### CODE REVIEW

**Review by eddiesarevalo — APPROVED** [review]
Works well. There  are 2 things missing we need to add in the near future. 1) Page Type and 2) Fix startExpanded not working on change.

**Comment by anilnatha** [comment]
@eddiesarevalo Could you clarify what you mean by adding "Page Type"? Do you mean adding a column to the component?

**Comment by anilnatha** [comment]
@eddiesarevalo I pushed a fix for the `startExpanded` issue you reported to the branch of this PR. Can you please try it again and let me know if the fix worked for you? I don't have a way to test this myself in the same manner you were testing it. My original test for this prop was working.

**Comment by anilnatha** [comment]
Received confirmation from @eddiesarevalo via Slack that the fix for the `starteExpanded` issue has been resolved.  Also spoke with Eddie about the "Page Type" issue and informed him that the featured needed for that has already been implemented. I provided an example of how to use the feature via Slack. Will merge this PR.

**Pull request merged**
