### PR TITLE
Make Header Responsive

### PR DESCRIPTION
**Pull request by eddiesarevalo**
## 🗒️ Summary
This pull request makes the header responsive.

-Added resize navbars on breakpoints.
-Added menus for small screen size.
-Replaced icons with wds icons.
-Title link is now passed in as a prop.
-Added the title first item with a red forward arrow icon to each menu item dropdown.
-Added forward and forward up icons.
-Fixed reverse arrow circle in small navbar menu.
-Removed unused code.

Extra:
-Removed explore-pds link.

## ⚙️ Test Data and/or Report
Follow the steps in the read me to build and run locally https://github.com/NASA-PDS/wds-react/edit/develop/README.md#getting-started. The only difference is in step 1 use branch header-responsive instead of develop. In summary download the wds and wds-react projects. Build them and then link them, after that build a test project in vite using typescript.

Note: make sure to rebuild the libraries. Build the new wds icons and the wds-react icons to get the forward icons.
Note: In `portal-wp` or another test app make sure to update the header tag to have the props like:
` <Header
      navItems={navItems}
      title={"Planetary Data System"}
      titleLink={"/"}
    />`

## ♻️ Related Issues
refs https://github.com/NASA-PDS/portal-wp-tasks/issues/72

### CODE REVIEW

**Comment by anilnatha** [comment]
@eddiesarevalo Awaiting discussion about the usage of the [new forward/diagonal](https://github.com/NASA-PDS/wds/pull/38) icons added to `wds` before final review of this PR is performed because the changes in this PR consume those icons.

**Comment by anilnatha** [comment]
This PR is awaiting completion of additional design work needed in Figma to finalize menu implementation.

**Comment by eddiesarevalo** [comment]
@anilnatha Updated the menu with the new designs. In order to run we no longer need to build icons. 

The new new invocations looks like this:

```js
<Header
        navItems={navItems}
        title={"Planetary Data System"}
        titleLink={"/"}
        subTitle={"Node Title"}
        subTitleLink={"/"}
/>
```

Or if no subtitle:

```js
<Header
        navItems={navItems}
        title={"Planetary Data System"}
        titleLink={"/"}
/>
```

Where navitems is the same as before.

Please try it out when you get a chance. There are so many moving parts to this I really could use a second and third pair of eyes to make sure the styles match the designs. Preferably designer eyes, perhaps @edwardbarraza?

**Comment by jordanpadams** [comment]
@eddiesarevalo are we blocked with this PR? @anilnatha can you provide feedback? also, can you maybe setup a quick 30 to demo for @newcomber to ensure the functionality is as expected?

**Comment by jordanpadams** [comment]
@eddiesarevalo or you could send over a quick video to @newcomber if that is easier.

**Comment by anilnatha** [comment]
Not blocked on this one, spoke with Eddie this morning about it. In the middle of reviewing it.

**Comment by anilnatha** [comment]
I've committed changes to the branch this PR references to resolve the issue we spoke of. The only minor thing I noticed now that the code is building is the alignment of the placeholder text in the search field on mobile/tablet breakpoints.

e.g.:

image

**Comment by anilnatha** [comment]
Awaiting input from Eddie after he resolves a menu issue that he will take up with Mike via slack.

**Comment by eddiesarevalo** [comment]
Spoke with Mike and decided to remove the top link in the submenus:

**Comment by eddiesarevalo** [comment]
Spoke with Mike and decided to remove the top link in the submenus:

**Comment by eddiesarevalo** [comment]
Spoke with Mike and decided to remove the top link in the submenus:

Screenshot 2024-07-24 at 12 41 56 PM

**Comment by anilnatha** [comment]
@eddiesarevalo Just reviewed the PR once more.

I fixed the build issue by resyncing the package-lock.json file from the `develop` branch.

However, there is an issue with the typography styles for mobile/tablet views in that the top level links and category names should be semi-bold, but they are set to regular.

**Review by anilnatha — APPROVED** [review]
LGTM!

**Pull request merged**
